# Generated by Django 4.2.1 on 2023-05-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=3000)),
                ("removeable", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MinecraftUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="post",
        ),
        migrations.AddField(
            model_name="item",
            name="minecraft_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.minecraftuser"
            ),
        ),
    ]
